MISSING_QUERY_PARAMETERS = "Missing 'owner' or 'repo' query parameters"
ERROR_FETCHING_ISSUES = "Error fetching issues"
ERROR_RATE_LIMIT_EXCEEDED = "Rate Limit Exceeded: 403"
ERROR_NOT_FOUND = "Not Found: 404"
ERROR_SERVER_ERROR = "Server Error: 500"
ERROR_UNEXPECTED = "Unexpected Error"
