version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: python app_cmd/server/main.py

  test:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    entrypoint: ["pytest"]
    command: ["tests"]
